version: 2
before:
  hooks:
    - go mod tidy

builds:
  - dir: cmd/logreport
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

archives:
  - name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
    files:
      - CREDITS
      - LICENSE
      - README.md
      - src: cmd/logreport/config.sample.yaml
        dst: logreport.yaml

nfpms:
  - id: logreport
    file_name_template: "{{ .ProjectName }}_{{ .Version }}-1_{{ .Arch }}"
    builds:
      - logreport 
    homepage: https://github.com/masa23/logreport
    maintainer: Masafumi Yamamoto <masa23@gmail.com>
    description: Summarize the log in LTSV format and input the result into graphite
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    section: admin
    scripts:
      preinstall: misc/scripts/preinstall.sh
      postinstall: misc/scripts/postinstall.sh
    contents:
      - dst: /lib/systemd/system/logreport.service
        src: misc/files/logreport.service
        type: config
      - dst: /etc/logreport/logreport.yaml
        src: cmd/logreport/config.sample.yaml
        type: config
      - dst: /usr/share/doc/logreport/CREDITS
        src: CREDITS
      - dst: /var/run/logreport
        type: dir
        file_info:
          mode: 0755
      - dst: /usr/share/doc/logreport
        type: dir
        file_info:
          mode: 0755
      - dst: /etc/logreport
        type: dir
        file_info:
          mode: 0700
