services:
  graphite:
    image: graphiteapp/graphite-statsd
    ports:
      - 127.0.0.1:3001:80
      - 127.0.0.1:2003:2003
    volumes:
      - ./misc/files/storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf

  influxdb:
    image: influxdb:2
    ports:
      - 127.0.0.1:8086:8086
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: password
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: admin-token
      DOCKER_INFLUXDB_INIT_ORG: admin
      DOCKER_INFLUXDB_INIT_BUCKET: bucket1

  victoriametrics:
    image: victoriametrics/victoria-metrics:v1.114.0
    ports:
      - 127.0.0.1:8428:8428
    command: ["-dedup.minScrapeInterval=1ms"]

  otelcol:
    image: otel/opentelemetry-collector-contrib:0.116.1
    command: ["--config=/etc/otelcol.yaml"]
    volumes:
      - ./misc/files/otelcol.yaml:/etc/otelcol.yaml
    restart: always
    ports:
      - 127.0.0.1:4317:4317
    depends_on:
      - influxdb

  grafana:
    image: grafana/grafana
    ports:
      - 127.0.0.1:3000:3000
