services:
  graphite:
    image: graphiteapp/graphite-statsd
    ports:
      - 127.0.0.1:3001:80
      - 127.0.0.1:2003:2003
    volumes:
      - ./misc/files/storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf

  prometheus:
    image: prom/prometheus:v3.0.1
    command:
      - --web.enable-remote-write-receiver
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
    - 127.0.0.1:9090:9090

  otelcol:
    image: otel/opentelemetry-collector-contrib:0.116.1
    command: ["--config=/etc/otelcol.yaml"]
    volumes:
    - ./misc/files/otelcol.yaml:/etc/otelcol.yaml
    restart: always
    ports:
    - 127.0.0.1:4317:4317
    depends_on:
      - prometheus
