# Daemon option
Debug: false
PidFile: "/var/run/logreport.pid"
ErrorLogFile: "/var/log/logreport.log"
LogBufferSize: 4096

# Read log file path. Posisiton file path.
LogFile: "/var/log/nginx/access.log"
PosFile: "/var/log/nginx/access.log.pos"

TimeColumn: "time_local"
TimeParse: "02/Jan/2006:15:04:05 -0700"
LogFormat: ltsv
# LogFormat: json

# metric send graphite (DEPRECATED)
Graphite:
  Host: "graphite.example.jp"
  Port: 2003
  Prefix: "sec.logreport.local"
  SendBuffer: 1000

Exporters:
  Graphite:
    Host: localhost
    Port: 2003
    Prefix: "sec.logreport.local"
    SendBuffer: 1000
  #OtlpGrpc:
  #  URL: addrs:///localhost:4317
  #  TLS:
  #    Insecure: true
  #  SendBuffer: 1000
  #  MaxRetryCount: 10
  #  RetryWait: 1s

# Report
Report:
  Interval: 1s
  Delay: 10s
  InitialReadPositionEnd: true

# Summary Metrics
Metrics:
  - Description: "status count"
    ItemName: "http.status"
    Type: "itemCount"
    LogColumn: "status"
    Filter:
      - LogColumn: "scheme"
        Values:
          - "http"
        Bool: true

  - Description: "status count"
    ItemName: "https.status"
    Type: "itemCount"
    LogColumn: "status"
    Filter:
      - LogColumn: "scheme"
        Values:
          - "https"
        Bool: true

  - Discription: "http request count"
    ItemName: "http.request"
    Type: "count"
    LogColumn: "scheme"
    Filter:
      - LogColumn: "scheme"
        Values:
          - "http"
        Bool: true

  - Discription: "https request count"
    ItemName: "https.request"
    Type: "count"
    LogColumn: "scheme"
    Filter:
      - LogColumn: "scheme"
        Values:
          - "https"
        Bool: true

  - Description: "hit counter"
    ItemName: "hit-count"
    Type: "itemCount"
    LogColumn: "upstream_cache_status"

  - Description: "bytes sent"
    ItemName: "bytes_sent"
    Type: "sum"
    DataType: "int"
    LogColumn: "bytes_sent"

  - Description: "max upstream request time"
    ItemName: "upstream_request_time_max"
    Type: "max"
    DataType: "float"
    LogColumn: "upstream_request_time"

  - Description: "min upstream request time"
    ItemName: "upstream_request_time_max"
    Type: "min"
    DataType: "float"
    LogColumn: "upstream_request_time"
